package com.dizzy.remake.core

data class RoomText(val prgOffset:Int,val english:String,val polish:String?=null)

object RoomTextCatalog {
    val verified = listOf(
        RoomText(0x19738,"HOME SWEET HOME!","WSZĘDZIE DOBRZE, ALE W DOMU NAJLEPIEJ!"),
        RoomText(0x1974E,"YOU ARE IN YOUR VERY OWN","JESTEŚ W SWOIM WŁASNYM"),
        RoomText(0x19767,"TREEHOUSE HUT, CARRYING","DOMKU NA DRZEWIE. NIESIESZ"),
        RoomText(0x19B27,"YOU ARE IN GRAND DIZZY'S","JESTEŚ W DOMKU GRAND DIZZY'EGO"),
        RoomText(0x19B40,"HUT NEAR A LARGE CAST IRON","OBOK WIELKIEGO ŻELIWNEGO"),
        RoomText(0x19B5B,"COOKING CAULDRON, CARRYING","KOTŁA. NIESIESZ"),
        RoomText(0x1A6C5,"YOU ARE IN A SMALL EERIE","JESTEŚ NA MAŁYM, POSĘPNYM"),
        RoomText(0x1A6F5,"GRAVEYARD, CARRYING","CMENTARZU. NIESIESZ"),
        RoomText(0x1A84B,"YOU ARE UNDER THE SEA NEAR","JESTEŚ POD WODĄ W POBLIŻU"),
        RoomText(0x1A87A,"PIRATE'S GALLEON, CARRYING","PIRACKIEGO GALEONU. NIESIESZ"),
        RoomText(0x1AE0D,"YOU ARE ON CASTLE STREET,","JESTEŚ NA CASTLE STREET,"),
        RoomText(0x1AE27,"WHERE YOU'LL FIND THE","GDZIE ZNAJDZIESZ"),
        RoomText(0x1AE3D,"SHOPKEEEPER, CARRYING","SKLEPIKARZA. NIESIESZ"),
        RoomText(0x1B134,"YOU'RE NEAR WIZARD ZAKS'","JESTEŚ W POBLIŻU"),
        RoomText(0x1B14D,"MAGICAL CLOUD CASTLE,","MAGICZNEGO ZAMKU ZAKSA W CHMURACH,"),
        RoomText(0x1B163,"CARRYING","NIESIESZ")
    )
}
