package com.dizzy.remake.tests

import com.dizzy.remake.core.OriginalObjectCatalog
import com.dizzy.remake.core.OriginalObject

fun main() {
    val all = OriginalObjectCatalog.all
    val sample = byteArrayOf(0x31,0xF0.toByte(),0x00,0x3C,0x48,0x8C.toByte(),0x13,0x05,0xAD.toByte(),0x00)
    val decoded = OriginalObject.decode(sample, 0)
    check(decoded == OriginalObject(49,240,0,60,35912,19,44293,0))
    val padded = byteArrayOf(0x55) + sample + byteArrayOf(0x66)
    check(OriginalObject.decode(padded, 1) == decoded)
    var shortDecodeRejected = false
    try { OriginalObject.decode(byteArrayOf(1,2,3), 0) } catch (_: IllegalArgumentException) { shortDecodeRejected = true }
    check(shortDecodeRejected)
    check(com.dizzy.remake.core.OriginalObject.BYTE_SIZE == 10)
    check(OriginalObjectCatalog.RECORD_COUNT == 64)
    check(OriginalObjectCatalog.TABLE_START_PRG_OFFSET == 259408)
    check(OriginalObjectCatalog.TABLE_CPU_ADDRESS == 0xF550)
    check(OriginalObjectCatalog.TABLE_END_EXCLUSIVE_PRG_OFFSET == 260048)
    check(OriginalObjectCatalog.TABLE_END_EXCLUSIVE_CPU_ADDRESS == 0xF7D0)
    check(OriginalObjectCatalog.CACHE_START_RAM == 0x05CF)
    check(OriginalObjectCatalog.CACHE_RECORD_SIZE == 5)
    check(OriginalObjectCatalog.CACHE_COPY_COUNT == 65)
    check(OriginalObjectCatalog.CACHE_SENTINEL_FIRST_BYTE == 0xFF)
    check(OriginalObjectCatalog.TABLE_END_EXCLUSIVE_PRG_OFFSET - OriginalObjectCatalog.TABLE_START_PRG_OFFSET == 640)
    check(OriginalObjectCatalog.RECORD_COUNT * com.dizzy.remake.core.OriginalObject.BYTE_SIZE == 640)
    check(all.size == 64)
    check(all.map { it.raw6 }.toSet() == (0..31).toSet())
    check(all.map { it.raw9 }.toSet() == (0..7).toSet())
    check(all.all { (it.raw45le ushr 8) in 0x80..0xAA })
    check(all.all { (it.raw78le ushr 8) in 0xAC..0xBD })
    check(all[0].raw0 == 255 && all[0].raw1 == 50 && all[0].raw45le == 32772)
    check(all[0].locationKey == 255)
    check(all[0].worldX == 50)
    check(all[0].spriteY == 40)
    check(all[0].graphicsSourceCpu == 0x8004)
    check(all[0].behaviorIndex == 0)
    check(all[1] == all[0])
    check(all[47].raw0 == 49 && all[47].raw1 == 240 && all[47].raw3 == 60)
    check(all[48].raw0 == 5 && all[48].raw1 == 148)
    check(all.last().raw0 == 19 && all.last().raw1 == 172)
    check(all.any { it.raw0 == 0 && it.raw1 == 100 && it.raw3 == 40 })
    check(all.any { it.raw0 == 48 && it.raw1 == 190 && it.raw3 == 64 })
    check(all.any { it.raw0 == 49 && it.raw1 == 240 && it.raw3 == 60 && it.raw45le == 35912 && it.raw78le == 44293 })
    check(OriginalObjectCatalog.forLocationKey(19).size == 3)
    check(OriginalObjectCatalog.forLocationKey(20).size == 3)
    check(OriginalObjectCatalog.forLocationKey(49).size == 1)
    check(OriginalObjectCatalog.forLocationKey(50).isEmpty())
    check(all.count { it.locationKey == 255 } == 2)
    check(all.filter { it.locationKey != 255 }.all { it.locationKey in 0..49 })
    check(all.all { it.worldX in 0..0x07FF })
    check(all.all { it.spriteY in 0..255 })
    check(all.map { it.behaviorIndex }.toSet() == (0..31).toSet())
    println("original object catalog self-test OK")
}
